### ISSUE TITLE
push_swap visualisation

### ISSUE THREAD

**Issue by elijahkash** [daniiomir/faq_for_school_21#4]
Hello!
Может стоит в "чекеры" добавить готовую визуализацию для push_swap, в которой можно легко посмотреть, как отработал собственный пушсвап.

> https://github.com/elijahkash/push_swap_gui

Может кому нибудь пригодится.

**Comment by daniiomir** [comment]
Привет!
Извиняюсь за долгое ожидание!
Ссылку добавил
